### ISSUE TITLE
请教论文中一些问题

### ISSUE THREAD

**Issue by wangjian124** [jumpycat/A-Secure-and-Dynamic-Multi-keyword-Ranked-Search-Scheme-over-Encrypted-Cloud-Data#1]
关于关键词提取是用什么工具呢，顺便想请教下论文中的一些问题，比如在数据用户查询时，根据idf生成的查询向量，是如何生成的，因为数据用户输入关键字发送给服务器后，服务器本身没法知道所有关键字的明文，所以没法计算idf值，难道是先发给数据所有者，由数据所有者生成trapdoor，再发给数据用户来跟服务器交互吗。。求指教

**Comment by jumpycat** [comment]
你好，这篇文章是我的导师很多年前的工作，我只是付费发布代码，并没有参与。具体可以咨询我导师邮箱xia_zhihua@163.com
